apiVersion: v1
kind: deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
    app: demo-voting-app
  spec:
    replicas: 1
    selector:
      metchlebels:
       name: redis-pod
       app: demo-voting-app
    template:
      metadata:
        name: redis-pod
        lebels:
          name: redis-pod
          app: demo-voting-app
      spec:    
       containers:
       - name: redis
         image: redis
         ports:
          - containerport: 6379
    
