apiVersion: v1
kind: deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
    app: demo-voting-app
  spec:
  replica: 1
  selector: 
    matchlebels:
      name: result-app-pod
      app: demo-voting-app
  template:
    name: voting-app-pod
    labels:
     name: voting-app-pod
     app: demo-voting-app
    spec:
    containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_result:v1
      ports:
       -containerport: 80
